version: '3'
services:
  privacyidea:
    image: ykorzikowski/privacyidea
    build: .
    environment:
      SQLALCHEMY_DATABASE_URI: "pymysql://user:password@11.12.13.14/privacyideadb"
      PI_WORKERS: 4
    volumes:
    - ./config:/config
